@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Sep 21 23:43:50 +0800 2026
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim fifo_2_10_tb_behav -key {Behavioral:sim_1:Functional:fifo_2_10_tb} -tclbatch fifo_2_10_tb.tcl -view D:/coding/verilog/xc7k70t/project_fifo/fifo_1_2_tb_behav.wcfg -log simulate.log"
call xsim  fifo_2_10_tb_behav -key {Behavioral:sim_1:Functional:fifo_2_10_tb} -tclbatch fifo_2_10_tb.tcl -view D:/coding/verilog/xc7k70t/project_fifo/fifo_1_2_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
