# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/coding/verilog/xc7k70t/project_fifo/project_fifo.srcs/sources_1/ip/fifo_36x128_fwft_sync/fifo_36x128_fwft_sync.xci
# IP: The module: 'fifo_36x128_fwft_sync' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/coding/verilog/xc7k70t/project_fifo/project_fifo.gen/sources_1/ip/fifo_36x128_fwft_sync/fifo_36x128_fwft_sync.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_36x128_fwft_sync'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/coding/verilog/xc7k70t/project_fifo/project_fifo.gen/sources_1/ip/fifo_36x128_fwft_sync/fifo_36x128_fwft_sync_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_36x128_fwft_sync'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/coding/verilog/xc7k70t/project_fifo/project_fifo.srcs/sources_1/ip/fifo_36x128_fwft_sync/fifo_36x128_fwft_sync.xci
# IP: The module: 'fifo_36x128_fwft_sync' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/coding/verilog/xc7k70t/project_fifo/project_fifo.gen/sources_1/ip/fifo_36x128_fwft_sync/fifo_36x128_fwft_sync.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_36x128_fwft_sync'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/coding/verilog/xc7k70t/project_fifo/project_fifo.gen/sources_1/ip/fifo_36x128_fwft_sync/fifo_36x128_fwft_sync_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_36x128_fwft_sync'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
