######################################################################
#
# File name : fifo_1_2_tb_compile.do
# Created on: Sun Sep 13 09:26:44 +0800 2026
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\software\\modeltech\\win64\\vlib modelsim_lib/work
D:\\software\\modeltech\\win64\\vlib modelsim_lib/msim

D:\\software\\modeltech\\win64\\vlib modelsim_lib/msim/xil_defaultlib

D:\\software\\modeltech\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

D:\\software\\modeltech\\win64\\vlog  -incr -work xil_defaultlib  \
"../../../../project_fifo.gen/sources_1/ip/fifo_16x64/sim/fifo_16x64.v" \
"../../../../project_fifo.srcs/sources_1/new/fifo_1_2.v" \
"../../../../project_fifo.srcs/sim_1/new/fifo_1_2_tb.v" \


# compile glbl module
D:\\software\\modeltech\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

